In [2]:
import pandas as pd


In [3]:
pd.__version__

'1.3.4'

In [15]:
df = pd.read_csv('housing.csv')

In [17]:
print(len(df.columns))

10


In [19]:
print(df.columns[df.isnull().any()])

Index(['total_bedrooms'], dtype='object')


In [21]:
print(df['ocean_proximity'].unique())

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [27]:
df1 = df.groupby('ocean_proximity')
df2 = df1.get_group("NEAR BAY")
print(df2['median_house_value'].mean())

259212.31179039303


In [28]:
print(df['total_bedrooms'].mean())

537.8705525375618


In [30]:
df1 = df['total_bedrooms'].fillna(value = 537.87)
print(df1)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64


In [32]:
print(df1.mean())

537.8705469961225


In [34]:
df1 = df.groupby('ocean_proximity')
df2 = df1.get_group("ISLAND")
df3 = df2[['housing_median_age','total_rooms','total_bedrooms']]
print(df2)
print(df3)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

In [35]:
import numpy as np
x = np.array([[27,1xt675,521],[52,2359,591],[52,2127,512],[52,996,264],[29,716,214]])
print(x)

[[  27 1675  521]
 [  52 2359  591]
 [  52 2127  512]
 [  52  996  264]
 [  29  716  214]]


In [38]:
import numpy as np
x = np.array([[27,1675,521],[52,2359,591],[52,2127,512],[52,996,264],[29,716,214]])
xt = x.transpose()
print(xt)

[[  27   52   52   52   29]
 [1675 2359 2127  996  716]
 [ 521  591  512  264  214]]


In [40]:
xtx = xt @ x
print(xtx)

[[    9682   351053    91357]
 [  351053 14399307  3772036]
 [   91357  3772036   998358]]


In [43]:
from numpy.linalg import inv
xtxinv = inv(xtx)
print(xtxinv)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [44]:
y = np.array([950,1300,800,1000,1300])
print(y)

[ 950 1300  800 1000 1300]


In [46]:
pre_w = xtxinv @ xt
w = pre_w @ y
print(w)

[23.12330961 -1.48124183  5.69922946]
